
USE QLCB
GO
SELECT * FROM KHACHHANG
SELECT * FROM DATCHO
SELECT * FROM LICHBAY
SELECT * FROM CHUYENBAY
SELECT * FROM MAYBAY
SELECT * FROM LOAIMB
SELECT * FROM KHANANG
SELECT * FROM NHANVIEN
SELECT * FROM PHANCONG
--Q51. Cho	biết mã	những	chuyến bay	đã bay	tất cả các máy bay	của hãng "Boeing".
SELECT DISTINCT LB.MACB
FROM LICHBAY LB
WHERE NOT EXISTS ((SELECT  LMB.MALOAI
					FROM LOAIMB LMB 
					WHERE LMB.HANGSX = 'Boeing' )
					EXCEPT
					(SELECT LB1.MALOAI
					FROM LICHBAY LB1
					WHERE LB1.MACB = LB.MACB)
					)
SELECT LB.MACB
FROM LICHBAY LB  JOIN LOAIMB LMB ON LMB.MALOAI = LB.MALOAI
WHERE LMB.HANGSX = 'Boeing'
GROUP BY LB.MACB
HAVING COUNT(DISTINCT LB.MALOAI) = (SELECT COUNT(*)
								FROM LOAIMB LMB1
								WHERE LMB1.HANGSX = 'Boeing')
--Q52. Cho	biết mã	và	tên	phi	công	có khả năng	lái	tất cả các máy bay	của hãng "Airbus".
-- BC: KHANANG(MANC,MALOAI)
-- C: LOAIMB(MALOAI) HSX = AIRBUS
-- KQ: NHANVIEN(MANV,TEN)
SELECT DISTINCT NV.MANV, NV.TEN
FROM NHANVIEN NV 
WHERE NV.LOAINV = 1 AND NOT EXISTS ( 
									(SELECT LMB.MALOAI
									FROM LOAIMB LMB
									WHERE LMB.HANGSX = N'Airbus'  )
										EXCEPT
									(SELECT KN.MALOAI
									FROM KHANANG KN
									WHERE KN.MANV = NV.MANV)
									)

SELECT DISTINCT NV.MANV, NV.TEN
FROM NHANVIEN NV JOIN KHANANG KN ON NV.MANV = KN.MANV
	JOIN LOAIMB LMB ON LMB.MALOAI = KN.MALOAI
WHERE NV.LOAINV = 1 AND  LMB.HANGSX = 'Airbus'
GROUP BY NV.MANV, NV.TEN
HAVING COUNT(DISTINCT LMB.MALOAI) = (SELECT COUNT( *)
									FROM LOAIMB LMB1
									WHERE LMB1.HANGSX = 'Airbus')

--Q53. Cho	biết tên nhân viên (không	phải là phi	công)	được phân	công	bay	vào	tất cả các chuyến bay có mã 100.
--BC: PHANCONG(MANV,MACB)
--C: LICHBAY(MACB) MACB =100
SELECT NV.MANV,NV.TEN
FROM NHANVIEN NV
WHERE NV.LOAINV = 0 AND NOT EXISTS((SELECT LB.MACB, LB.NGAYDI
									FROM LICHBAY LB
									WHERE LB.MACB = '100')
									
									EXCEPT 

									(SELECT PC.MACB, PC.NGAYDI
									FROM PHANCONG PC
									WHERE PC.MANV = NV.MANV )
									)
SELECT NV.MANV, NV.TEN
FROM NHANVIEN NV JOIN PHANCONG PC ON PC.MANV = NV.MANV
		JOIN LICHBAY LB ON LB.MACB = PC.MACB AND PC.NGAYDI = LB.NGAYDI
WHERE NV.LOAINV = 0 AND LB.MACB ='100'
GROUP BY NV.MANV, NV.TEN
HAVING COUNT(DISTINCT LB.NGAYDI) =(SELECT COUNT(*)
								FROM LICHBAY LB1
								WHERE LB1.MACB = '100')
--Q54. Cho	biết	ngày	đi	nào	mà	có	tất	cả các	loại	máy	bay	của	hãng	"Boeing"	tham	gia.
SELECT LB.NGAYDI
FROM LICHBAY LB
WHERE NOT EXISTS ((SELECT  MB.MALOAI
					FROM LOAIMB LMB JOIN MAYBAY MB ON LMB.MALOAI = MB.MALOAI
					WHERE LMB.HANGSX = 'Boeing' )
					EXCEPT
					(SELECT LB1.MALOAI
					FROM LICHBAY LB1
					WHERE LB1.NGAYDI = LB.NGAYDI)
					)
SELECT LB.NGAYDI
FROM LICHBAY LB JOIN MAYBAY MB ON LB.SOHIEU = MB.SOHIEU  AND LB.MALOAI = MB.MALOAI
	JOIN LOAIMB LMB ON MB.MALOAI = LMB.MALOAI
WHERE LMB.HANGSX = 'Boeing'
GROUP BY LB.NGAYDI
HAVING COUNT(DISTINCT LB.MALOAI) = (SELECT COUNT(*)
								FROM LOAIMB LMB1
								WHERE LMB1.HANGSX = 'Boeing')
--Q55. Cho	biết	loại	máy	bay	của	hãng	"Boeing"	nào	có	tham	gia	vào	tất	cả các	ngày	đi.
SELECT LMB.MALOAI
FROM LOAIMB LMB 
WHERE LMB.HANGSX = 'Boeing' AND NOT EXISTS ((SELECT  DISTINCT LB.NGAYDI
											FROM  LICHBAY LB)
											EXCEPT
											(SELECT LB1.NGAYDI
											FROM LICHBAY LB1
											WHERE LB1.MALOAI = LMB.MALOAI)
											)
SELECT LB.MALOAI
FROM LICHBAY LB JOIN MAYBAY MB ON LB.SOHIEU = MB.SOHIEU  AND LB.MALOAI = MB.MALOAI
	JOIN LOAIMB LMB ON MB.MALOAI = LMB.MALOAI
WHERE LMB.HANGSX = 'Boeing'
GROUP BY LB.MALOAI
HAVING COUNT(DISTINCT LB.NGAYDI) = (SELECT COUNT(DISTINCT LB1.NGAYDI)
								FROM LICHBAY LB1)
--Q56. Cho	biết	mã	và	tên	các	khách	hàng	có	đặt	chổ trong	tất	cả các	ngày	từ 31/10/2000	đến	1/1/2000
SELECT	KH.MAKH, KH.TEN
FROM KHACHHANG KH
WHERE NOT EXISTS ((SELECT LB.NGAYDI
					FROM LICHBAY LB
					WHERE LB.NGAYDI >= '2000-10-31' and LB.NGAYDI < '2000-11-01')
					EXCEPT
					(SELECT DC.NGAYDI
					FROM DATCHO DC
					WHERE DC.MAKH = KH.MAKH))

SELECT KH.MAKH, KH.TEN
FROM KHACHHANG KH JOIN DATCHO DC ON DC.MAKH = KH.MAKH
WHERE DC.NGAYDI >= '2000-10-31' and DC.NGAYDI < '2000-11-01'
GROUP BY KH.MAKH, KH.TEN
HAVING COUNT(DISTINCT DC.NGAYDI) = (SELECT COUNT(DISTINCT LB.NGAYDI)
									FROM LICHBAY LB
									WHERE LB.NGAYDI >= '2000-10-31' and LB.NGAYDI < '2000-11-01')				
--Q57. Cho	biết	mã	và	tên	phi	công	không	có	khả năng	lái	được	tất	cả các	máy	bay	của	hãng "Airbus"
SELECT DISTINCT NV.MANV, NV.TEN
FROM NHANVIEN NV 
WHERE NV.LOAINV = 1 AND EXISTS ( 
									(SELECT LMB.MALOAI
									FROM LOAIMB LMB
									WHERE LMB.HANGSX = N'Airbus'  )
										EXCEPT
									(SELECT KN.MALOAI
									FROM KHANANG KN
									WHERE KN.MANV = NV.MANV)
									)

SELECT DISTINCT NV.MANV, NV.TEN
FROM NHANVIEN NV JOIN KHANANG KN ON NV.MANV = KN.MANV
	JOIN LOAIMB LMB ON LMB.MALOAI = KN.MALOAI
WHERE NV.LOAINV = 1 AND  LMB.HANGSX = 'Airbus'
GROUP BY NV.MANV, NV.TEN
HAVING COUNT(DISTINCT LMB.MALOAI) != (SELECT COUNT( *)
									FROM LOAIMB LMB1
									WHERE LMB1.HANGSX = 'Airbus')
--Q58. Cho	biết	sân	bay	nào	đã	có	tất	cả các	loại	máy	bay	của	hãng	"Boeing"	xuất	phát.
--BC: CHUYENBAY(SBDI,MALOAI)
--C: LOAIMB(MALOAI)

SELECT CB.SBDI
FROM CHUYENBAY CB
WHERE NOT EXISTS ((SELECT  MB.MALOAI
					FROM LOAIMB LMB JOIN MAYBAY MB ON LMB.MALOAI = MB.MALOAI
					WHERE LMB.HANGSX = 'Boeing' )
					EXCEPT
					(SELECT LB1.MALOAI
					FROM LICHBAY LB1 JOIN CHUYENBAY CB1 ON LB1.MACB = CB1.MACB
					WHERE CB1.SBDI = CB.SBDI)
					)
SELECT CB.SBDI
FROM LICHBAY LB JOIN CHUYENBAY CB ON LB.MACB = CB.MACB
	 JOIN LOAIMB LMB ON LMB.MALOAI = LB.MALOAI
WHERE LMB.HANGSX = 'Boeing'
GROUP BY CB.SBDI
HAVING COUNT(DISTINCT LB.MALOAI) = (SELECT COUNT(*)
								FROM LOAIMB LMB1
								WHERE LMB1.HANGSX = 'Boeing')