
USE QLDT
GO
--Q35. Cho	biết	mức	lương	cao	nhất	của	các	giảng	viên.
SELECT DISTINCT GV.LUONG
FROM GIAOVIEN GV
WHERE GV.LUONG >= ALL(SELECT GV2.LUONG
					FROM GIAOVIEN GV2)
--Q36. Cho	biết	những	giáo	viên	có	lương	lớn	nhất.
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG >= ALL(SELECT GV2.LUONG
					FROM GIAOVIEN GV2)
--Q37. Cho	biết	lương	cao	nhất	trong	bộ môn	“HTTT”.
SELECT GV.LUONG
FROM GIAOVIEN GV
WHERE  GV.MABM = 'HTTT' AND GV.LUONG >= ALL(SELECT GV2.LUONG
										FROM GIAOVIEN GV2
										WHERE GV2.MABM = 'HTTT')
--Q38. Cho	biết	tên	giáo	viên	lớn	tuổi	nhất	của	bộ môn	Hệ thống	thông	tin.
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE  BM.TENBM = N'HỆ THỐNG THÔNG TIN' AND DATEDIFF(YEAR,GV.NGSINH,GETDATE()) >= ALL(SELECT DATEDIFF(YEAR,GV2.NGSINH,GETDATE())
																						FROM GIAOVIEN GV2
																						WHERE GV2.MABM = GV.MABM)
--Q39. Cho	biết	tên	giáo	viên	nhỏ tuổi	nhất	khoa	Công	nghệ thông	tin.
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
		JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
WHERE  K.TENKHOA = N'CÔNG NGHỆ THÔNG TIN' AND DATEDIFF(YEAR,GV.NGSINH,GETDATE()) <= ALL(SELECT DATEDIFF(YEAR,GV2.NGSINH,GETDATE())
																						FROM GIAOVIEN GV2 JOIN BOMON BM2 ON BM2.MABM = GV2.MABM
																						WHERE BM.MAKHOA = BM2.MAKHOA)
--Q40. Cho	biết	tên	giáo	viên	và	tên	khoa	của	giáo	viên	có	lương	cao	nhất.
SELECT GV.HOTEN, K.TENKHOA
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
		JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
WHERE GV.LUONG >= ALL(SELECT GV2.LUONG
					FROM GIAOVIEN GV2)
--Q41. Cho	biết	những	giáo	viên	có	lương	lớn	nhất	trong	bộ môn	của	họ.
SELECT GV.HOTEN, BM.TENBM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE GV.LUONG >= ALL(SELECT GV2.LUONG
					FROM GIAOVIEN GV2
					WHERE GV2.MABM = GV.MABM)
--Q42. Cho	biết	tên	những	đề tài	mà	giáo	viên	Nguyễn	Hoài	An	chưa	tham	gia.
SELECT DT.TENDT
FROM DETAI DT
WHERE DT.MADT NOT IN(SELECT TG.MADT
						FROM THAMGIADT TG JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
						WHERE GV.HOTEN = N'NGUYỄN HOÀI AN')
--Q43. Cho	biết	những	đề tài	mà	giáo	viên	Nguyễn	Hoài	An	chưa	tham	gia.	Xuất	ra	tên	đề tài,	tên	người	chủ nhiệm	đề tài.
SELECT DT.TENDT, GV.HOTEN
FROM DETAI DT JOIN GIAOVIEN GV ON DT.GVCNDT = GV.MAGV
WHERE DT.MADT NOT IN(SELECT TG.MADT
						FROM THAMGIADT TG JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
						WHERE GV.HOTEN = N'NGUYỄN HOÀI AN')
--Q44. Cho	biết	tên	những	giáo	viên	khoa	Công	nghệ thông	tin	mà	chưa	tham	gia	đề tài	nào.
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
	JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
WHERE K.TENKHOA = N'CÔNG NGHỆ THÔNG TIN' AND MAGV NOT IN (SELECT TG.MAGV
															FROM THAMGIADT TG)
--Q45. Tìm	những	giáo	viên	không	tham	gia	bất	kỳ đề tài	nào
SELECT *
FROM GIAOVIEN
WHERE MAGV NOT IN(SELECT TG.MAGV
				FROM THAMGIADT TG)
--Q46. Cho	biết	giáo	viên	có	lương	lớn	hơn	lương	của	giáo	viên	“Nguyễn	Hoài	An”
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG > (SELECT GV2.LUONG
				FROM GIAOVIEN GV2
				WHERE GV2.HOTEN = N'NGUYỄN HOÀI AN')
--Q47. Tìm	những trưởng	bộ môn	tham	gia	tối	thiểu	1	đề tài
SELECT GV.*
FROM GIAOVIEN GV JOIN BOMON BM ON BM.TRUONGBM = GV.MAGV
WHERE EXISTS (SELECT *
			FROM THAMGIADT TG
			WHERE TG.MAGV = GV.MAGV)
--Q48. Tìm	giáo	viên	trùng	tên	và	cùng	giới	tính	với	giáo	viên	khác	trong	cùng	bộ môn
SELECT GV.*
FROM GIAOVIEN GV 
WHERE EXISTS(SELECT*
			FROM GIAOVIEN GV2
			WHERE GV2.HOTEN = GV.HOTEN AND GV.PHAI = GV2.PHAI AND GV.MAGV != GV2.MAGV)
--Q49. Tìm	những	giáo	viên	có	lương	lớn	hơn	lương	của	ít	nhất	một	giáo	viên	bộ môn	“Công nghệ phần	mềm”
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG > ANY(SELECT GV2.LUONG
					FROM GIAOVIEN GV2 JOIN BOMON BM ON GV2.MABM = BM.MABM
					WHERE BM.TENBM = N'CÔNG NGHỆ PHẦN MỀM')
SELECT * FROM BOMON
SELECT* FROM GIAOVIEN
--Q50. Tìm	những	giáo	viên	có	lương	lớn	hơn	lương	của	tất	cả giáo	viên	thuộc	bộ môn	“Hệ thống	thông	tin”
SELECT GV.*
FROM GIAOVIEN GV
WHERE GV.LUONG > ALL(SELECT GV2.LUONG
					FROM GIAOVIEN GV2 JOIN BOMON BM ON GV2.MABM = BM.MABM
					WHERE BM.TENBM = N'Hệ thống thông tin')
--Q51. Cho	biết	tên	khoa	có	đông	giáo	viên	nhất
SELECT K.MAKHOA,K.TENKHOA
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
	JOIN KHOA K ON BM.MAKHOA = K.MAKHOA
GROUP BY K.MAKHOA,K.TENKHOA
HAVING COUNT(GV.MAGV) >= ALL(SELECT COUNT(GV2.MAGV)
						FROM GIAOVIEN GV2 JOIN BOMON BM2 ON GV2.MABM = BM2.MABM
							JOIN KHOA K2 ON BM2.MAKHOA = K2.MAKHOA
						GROUP BY K2.MAKHOA)
--Q52. Cho	biết	họ tên	giáo	viên chủ nhiệm	nhiều	đề tài	nhất
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DT.MADT) >=ALL( SELECT COUNT(DT2.MADT)
							FROM GIAOVIEN GV2 JOIN DETAI DT2 ON GV2.MAGV = DT2.GVCNDT
							GROUP BY GV2.MAGV)
SELECT * FROM DETAI
--Q53. Cho	biết	mã	bộ môn	có	nhiều	giáo	viên	nhất
SELECT BM.MABM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
GROUP BY BM.MABM
HAVING COUNT(GV.MAGV) >= ALL(SELECT COUNT(GV2.MAGV)
						FROM GIAOVIEN GV2 JOIN BOMON BM2 ON GV2.MABM = BM2.MABM
						GROUP BY BM2.MABM)
--Q54. Cho	biết	tên	giáo	viên	và	tên	bộ môn	của	giáo	viên	tham	gia	nhiều	đề tài	nhất.
SELECT GV.HOTEN, BM.TENBM
FROM THAMGIADT TG JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
	JOIN BOMON BM ON GV.MABM = BM.MABM
GROUP BY GV.MAGV, GV.HOTEN, BM.TENBM
HAVING COUNT(TG.MADT) >= ALL( SELECT COUNT(TG2.MADT)
								FROM THAMGIADT TG2 JOIN GIAOVIEN GV2 ON GV2.MAGV = TG2.MAGV
								GROUP BY GV2.MAGV)
--Q55. Cho	biết	tên	giáo	viên	tham	gia	nhiều	đề tài	nhất	của	bộ môn	HTTT.
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
WHERE GV.MABM = 'HTTT'
GROUP BY GV.MAGV,GV.HOTEN
HAVING COUNT(TG.MADT) >= ALL( SELECT COUNT(TG2.MADT)
							FROM GIAOVIEN GV2 JOIN THAMGIADT TG2 ON TG2.MAGV = GV2.MAGV
							WHERE GV2.MABM = 'HTTT'
							GROUP BY GV2.MAGV)
--Q56. Cho	biết	tên	giáo	viên	và	tên	bộ môn	của	giáo	viên	có	nhiều	người	thân	nhất.
SELECT GV.HOTEN, BM.TENBM,COUNT(NT.TEN) SONT
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM 
	JOIN NGUOITHAN NT ON NT.MAGV = GV.MAGV
GROUP BY GV.MAGV, GV.HOTEN, BM.TENBM
HAVING COUNT(NT.TEN) >= ALL(SELECT COUNT(NT2.TEN)
						FROM GIAOVIEN GV2 JOIN NGUOITHAN NT2 ON NT2.MAGV = GV2.MAGV
						GROUP BY GV2.MAGV)
--Q57. Cho	biết	tên	trưởng	bộ môn	mà	chủ nhiệm	nhiều	đề tài	nhất
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM
	JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DT.MADT) >= ALL( SELECT COUNT(DT2.MADT)
								FROM GIAOVIEN GV2 JOIN BOMON BM2 ON GV2.MAGV = BM2.TRUONGBM
									JOIN DETAI DT2 ON GV2.MAGV = DT2.GVCNDT
								GROUP BY GV2.MAGV)
