USE QLDT
GO
SELECT * FROM BOMON
SELECT * FROM CHUDE
SELECT * FROM CONGVIEC
SELECT * FROM DETAI
SELECT * FROM GIAOVIEN
SELECT * FROM GV_DT
SELECT * FROM KHOA
SELECT * FROM NGUOITHAN
SELECT * FROM THAMGIADT
--Q58. Cho	biết	tên	giáo	viên	nào	mà	tham	gia	đề tài đủ tất	cả các	chủ đề.
--BC: THAMGIADT, DETAI(MAGV,MACD)
-- C: CHUDE(MACD)
-- GIAOVIEN(MAGV)
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
					(SELECT CD.MACD FROM CHUDE CD)
					EXCEPT
					(SELECT DISTINCT DT.MACD
					FROM THAMGIADT TG JOIN DETAI DT ON TG.MADT = DT.MADT
					WHERE TG.MAGV = GV.MAGV )
					)
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (
									SELECT COUNT(DISTINCT DT.MADT)
									FROM DETAI DT
									)

--Q59. Cho	biết	tên	đề tài	nào	mà	được	tất	cả các	giáo	viên	của	bộ môn	HTTT	tham	gia.
-- BC: TGDT (MAGV,MADT)
--C : GIAOVIEN THUOC HTTT(MAGV)
-- KQ DETAI (MADT, TENDT)
SELECT DT.MADT, DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS(
				(SELECT DISTINCT GV.MAGV FROM GIAOVIEN GV WHERE GV.MABM = 'HTTT')
				EXCEPT
				(SELECT TG.MAGV
				FROM THAMGIADT TG 
				WHERE TG.MADT = DT.MADT)
				)
				

--HAVING COUNT
SELECT DT.MADT, DT.TENDT
FROM DETAI DT	JOIN THAMGIADT TG ON TG.MADT = DT.MADT
	JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
WHERE GV.MABM = 'HTTT'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT TG.MAGV) = (
									SELECT COUNT(DISTINCT GV2.MAGV)
									FROM GIAOVIEN GV2
									WHERE GV2.MABM = 'HTTT'
									)


--Q60. Cho	biết	tên	đề tài	có	tất	cả giảng	viên	bộ môn	“Hệ thống	thông	tin”	tham	gia
SELECT DT.MADT, DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS(
				(SELECT DISTINCT GV.MAGV 
				FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM = GV.MABM
				WHERE BM.TENBM = N'Hệ thống thông tin')
				EXCEPT
				(SELECT TG.MAGV
				FROM THAMGIADT TG 
				WHERE TG.MADT = DT.MADT)
				)
-- HAVING COUNT
SELECT DT.MADT, DT.TENDT
FROM DETAI DT	JOIN THAMGIADT TG ON TG.MADT = DT.MADT
	JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
	JOIN BOMON BM ON BM.MABM = GV.MABM
WHERE BM.TENBM = N'Hệ thống thông tin'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT TG.MAGV) = (
									SELECT COUNT(DISTINCT GV2.MAGV)
									FROM GIAOVIEN GV2 JOIN BOMON BM2 ON GV2.MABM = BM2.MABM
									WHERE BM2.TENBM = N'Hệ thống thông tin'
									)
--Q61. Cho	biết	giáo	viên	nào	đã	tham	gia	tất	cả các	đề tài	có	mã	chủ đề là	QLGD.
--BC: THAMGIADT, DETAI(MAGC,MACD)
--C: CHUDE(MACD)
--KQ: GIAOVIEN(MAGV)
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
					(SELECT DT.MADT FROM DETAI DT WHERE DT.MACD = 'QLGD')
					EXCEPT
					(SELECT DT2.MADT
					FROM THAMGIADT TG JOIN DETAI DT2 ON TG.MADT = DT2.MADT
					WHERE TG.MAGV = GV.MAGV
					)
					)
					AND GV.MAGV IN (SELECT TG2.MAGV FROM THAMGIADT TG2)

SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
		JOIN DETAI DT ON DT.MADT = TG.MADT
WHERE DT.MACD ='QLGD'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MADT) = ( SELECT COUNT(*)
									FROM DETAI DT2
									WHERE DT2.MACD = 'QLGD')
--Q62. Cho	biết tên giáo viên nào	tham gia tất	cả các	đề tài	mà	giáo	viên	Trần	Trà	Hương	đã	tham	gia.
--BC: GIAOVIEN , THAM GIADT(MAGV,MADT)
--C:  THAMGIADT, GIAOIEN MA HOTEN = TTH (MADT)
-- KQ: GIAOVIEN (MAGV)
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
					(SELECT TG.MADT 
					FROM GIAOVIEN GV2 JOIN THAMGIADT TG ON TG.MAGV = GV2.MAGV
					WHERE GV2.HOTEN =N'Trần Trà Hương')
					EXCEPT
					(SELECT TG2.MADT
					FROM THAMGIADT TG2
					WHERE GV.MAGV = TG2.MAGV)
					)
					AND GV.HOTEN !=N'Trần Trà Hương'
-- HAVING COUNT
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE TG.MADT IN (SELECT TG2.MADT
					FROM GIAOVIEN GV2 JOIN THAMGIADT TG2 ON GV2.MAGV = TG2.MAGV
					WHERE GV2.HOTEN = N'Trần Trà Hương')
					AND GV.HOTEN != N'Trần Trà Hương'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (SELECT TG3.MADT
								FROM GIAOVIEN GV3 JOIN THAMGIADT TG3 ON GV3.MAGV = TG3.MAGV
								WHERE GV3.HOTEN = N'Trần Trà Hương')

--Q63. Cho	biết	tên	đề tài	nào	mà	được	tất	cả các	giáo	viên	của	bộ môn	Hóa	Hữu	Cơ	tham	gia.
SELECT DT.MADT, DT.TENDT
FROM DETAI DT 
WHERE NOT EXISTS(
				(SELECT DISTINCT GV.MAGV 
				FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM = GV.MABM
				WHERE BM.TENBM = N'HÓA HỮU CƠ') 
				EXCEPT
				(SELECT TG.MAGV
				FROM THAMGIADT TG 
				WHERE TG.MADT = DT.MADT)
				)
-- HAVING COUNT
SELECT DT.MADT, DT.TENDT
FROM DETAI DT	JOIN THAMGIADT TG ON TG.MADT = DT.MADT
	JOIN GIAOVIEN GV ON GV.MAGV = TG.MAGV
	JOIN BOMON BM ON BM.MABM = GV.MABM
WHERE BM.TENBM = N'HÓA HỮU CƠ'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT TG.MAGV) = (
									SELECT COUNT(DISTINCT GV2.MAGV)
									FROM GIAOVIEN GV2 JOIN BOMON BM2 ON GV2.MABM = BM2.MABM
									WHERE BM2.TENBM =  N'HÓA HỮU CƠ'
									)
--Q64. Cho	biết	tên	giáo	viên	nào	mà	tham	gia	tất	cả các	công	việc	của	đề tài	006.
--BC: THAMGIADT(STT,MAGV) MADT = 006
--C: CONGVIEC(SOTT)
--KQ: GIAOVIEN(MAGV) -> XUẤT RA HỌ TÊN
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG2 ON TG2.MAGV = GV.MAGV
WHERE NOT EXISTS (
					(SELECT CV.SOTT  FROM CONGVIEC CV WHERE CV.MADT = '006')
					EXCEPT
					(SELECT TG.STT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV AND TG.MADT ='006')
					) 
-- HAVING COUNT
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
	JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE TG.MADT = '006'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.STT) = ( SELECT COUNT(DISTINCT SOTT)
									FROM CONGVIEC
									WHERE MADT ='006')

--Q65. Cho	biết	giáo	viên	nào	đã	tham	gia	tất	cả các	đề tài	của	chủ đề Ứng	dụng	công	nghệ.
-- BC: THAMGIADT(MAGV,MADT) 
--C: DETAI, CHUDE(MADT)  TENCD =''
-- KQ: GIAOVIEN *

SELECT *
FROM GIAOVIEN GV
WHERE NOT EXISTS (
					(SELECT DISTINCT DT.MADT 
					FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
					WHERE CD.TENCD = N'Ứng dụng công nghệ')
					EXCEPT 
					(SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV)
					)
-- HAVING COUNT
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
	JOIN DETAI DT ON DT.MADT =TG.MADT
	JOIN CHUDE CD ON CD.MACD = DT.MACD
WHERE CD.TENCD = N'Ứng dụng công nghệ'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(DISTINCT DT1.MADT)
									FROM DETAI DT1 JOIN CHUDE CD1 ON CD1.MACD = DT1.MACD
									WHERE CD1.TENCD = N'Ứng dụng công nghệ')

--Q66. Cho	biết	tên	giáo	viên	nào	đã	tham	gia	tất	cả các	đề tài	của	do	Trần	Trà	Hương	làm	chủ nhiệm.
-- BC THAMGIADT(MAGV, MADT)
-- C: DETAI, GIAOVIEN (MADT)  HOTEN = ''
-- KQ: GIAOVIEN(HOTEN)
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
					(SELECT DISTINCT DT.MADT 
					FROM DETAI DT JOIN GIAOVIEN GVCN ON DT.GVCNDT = GVCN.MAGV
					WHERE GVCN.HOTEN = N'Trần Trà Hương')
					EXCEPT 
					(SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV)
					)

--HAVING COUNT
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
	JOIN DETAI DT ON DT.MADT =TG.MADT
	JOIN GIAOVIEN GVCN ON GVCN.MAGV = DT.GVCNDT
WHERE GVCN.HOTEN = N'Trần Trà Hương'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(DISTINCT DT1.MADT)
									FROM DETAI DT1 JOIN GIAOVIEN GVCN1 ON GVCN1.MAGV = DT1.GVCNDT
									WHERE GVCN1.HOTEN = N'Trần Trà Hương')
--Q67. Cho	biết	tên	đề tài	nào	mà	được	tất	cả các	giáo	viên	của	khoa	CNTT	tham	gia.
--BC: THAMDT(MAGV,MADT)
--C: GIAOVIEN, BOMON (MAGV) BM.K = CNTT
--KQ: DETAI(TENDT)
SELECT DT.MADT, DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
					(SELECT DISTINCT GV.MAGV
					FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM = GV.MABM
					WHERE BM.MAKHOA = 'CNTT')
					EXCEPT 
					(SELECT TG.MAGV
					FROM THAMGIADT TG
					WHERE TG.MAGV = DT.MADT)
					)

--HAVING COUNT
SELECT DT.MADT, DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG  ON DT.MADT =TG.MADT
	JOIN GIAOVIEN GV ON GV.MAGV = DT.GVCNDT
	JOIN BOMON BM ON BM.MABM = GV.MABM
WHERE BM.MAKHOA = 'CNTT'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (SELECT COUNT(DISTINCT GV1.MAGV)
								FROM GIAOVIEN GV1 JOIN BOMON BM1 ON BM1.MABM = GV1.MABM
								WHERE BM1.MAKHOA = 'CNTT')

--Q68. Cho	biết	tên	giáo	viên	nào	mà	tham	gia	tất	cả các	công	việc	của	đề tài	Nghiên	cứu	tế bào	gốc.

SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG2 ON TG2.MAGV = GV.MAGV
WHERE NOT EXISTS (
					(SELECT CV.SOTT  
					FROM CONGVIEC CV JOIN DETAI DT ON DT.MADT = CV.MADT
					WHERE DT.TENDT = N'Nghiên cứu tế bào gốc')
					EXCEPT
					(SELECT TG.STT
					FROM THAMGIADT TG JOIN DETAI DT1 ON DT1.MADT = TG.MADT
					WHERE TG.MAGV = GV.MAGV AND DT1.TENDT = N'Nghiên cứu tế bào gốc')
					) 
-- HAVING COUNT
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
	JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
	JOIN DETAI DT ON DT.MADT = TG.MADT
WHERE DT.TENDT = N'Nghiên cứu tế bào gốc'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.STT) = ( SELECT COUNT(DISTINCT CV.SOTT)
									FROM CONGVIEC CV JOIN DETAI DT1 ON DT1.MADT = CV.MADT
									WHERE DT1.TENDT = N'Nghiên cứu tế bào gốc')
--Q69. Tìm	tên	các	giáo	viên	được	phân	công	làm	tất	cả các	đề tài	có	kinh	phí	trên	100	triệu?
--BC: THAMGIADT(MAGV,MADT)
--C: DETAI(MADT) KINH PHI >100
--KQ :GIAO VIEN(MAGV)
SELECT *
FROM GIAOVIEN GV
WHERE NOT EXISTS (
					(SELECT DISTINCT DT.MADT 
					FROM DETAI DT 
					WHERE DT.KINHPHI >100)
					EXCEPT 
					(SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV)
					)
-- HAVING COUNT
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
	JOIN DETAI DT ON DT.MADT =TG.MADT
WHERE DT.KINHPHI >100
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(DISTINCT DT1.MADT)
									FROM DETAI DT1 
									WHERE DT1.KINHPHI > 100)
--Q70. Cho	biết	tên	đề tài	nào	mà	được	tất	cả các	giáo	viên	của	khoa	Sinh	Học	tham	gia.
SELECT DT.MADT, DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
					(SELECT DISTINCT GV.MAGV
					FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM = GV.MABM 
						JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
					WHERE K.TENKHOA = N'SINH HỌC')
					EXCEPT 
					(SELECT TG.MAGV
					FROM THAMGIADT TG
					WHERE TG.MAGV = DT.MADT)
					)

--HAVING COUNT
SELECT DT.MADT, DT.TENDT
FROM DETAI DT JOIN THAMGIADT TG  ON DT.MADT =TG.MADT
	JOIN GIAOVIEN GV ON GV.MAGV = DT.GVCNDT
	JOIN BOMON BM ON BM.MABM = GV.MABM
	JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
WHERE K.TENKHOA = N'SINH HỌC'
GROUP BY DT.MADT, DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV) = (SELECT COUNT(DISTINCT GV1.MAGV)
									FROM GIAOVIEN GV1 JOIN BOMON BM1 ON BM1.MABM = GV1.MABM
									JOIN KHOA K1 ON K1.MAKHOA = BM1.MAKHOA
								WHERE K1.TENKHOA = N'SINH HỌC')
--Q71. Cho	biết	mã	số,	họ tên,	ngày	sinh	của	giáo	viên	tham	gia	tất	cả các	công	việc	của	đề tài	
--“Ứng	dụng	hóa	học	xanh”.
SELECT DISTINCT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV JOIN THAMGIADT TG2 ON TG2.MAGV = GV.MAGV
WHERE NOT EXISTS (
					(SELECT CV.SOTT  
					FROM CONGVIEC CV JOIN DETAI DT ON DT.MADT = CV.MADT
					WHERE DT.TENDT = N'Ứng dụng hóa học xanh')
					EXCEPT
					(SELECT TG.STT
					FROM THAMGIADT TG JOIN DETAI DT1 ON DT1.MADT = TG.MADT
					WHERE TG.MAGV = GV.MAGV AND DT1.TENDT = N'Ứng dụng hóa học xanh')
					) 
-- HAVING COUNT
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV
	JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
	JOIN DETAI DT ON DT.MADT = TG.MADT
WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
GROUP BY GV.MAGV, GV.HOTEN, GV.NGSINH
HAVING COUNT(DISTINCT TG.STT) = ( SELECT COUNT(DISTINCT CV.SOTT)
									FROM CONGVIEC CV JOIN DETAI DT1 ON DT1.MADT = CV.MADT
									WHERE DT1.TENDT = N'Ứng dụng hóa học xanh')
--Q72. Cho	biết	mã	số,	họ tên,	tên	bộ môn	và	tên	người	quản	lý	chuyên	môn	của	giáo	viên	
--tham	gia	tất	cả các	đề tài	thuộc	chủ đề “Nghiên	cứu	phát	triển”.
SELECT GVQL.MAGV, GVQL.HOTEN, BM.TENBM
FROM GIAOVIEN TTGV JOIN GIAOVIEN GVQL ON TTGV.GVQLCM = GVQL.MAGV
	JOIN BOMON BM ON GVQL.MABM = BM.MABM
WHERE TTGV.MAGV IN (
					SELECT GV.MAGV
					FROM GIAOVIEN GV
					WHERE NOT EXISTS (
										(SELECT DISTINCT DT.MADT 
										FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
										WHERE CD.TENCD = N'Nghiên cứu phát triển')
										EXCEPT 
										(SELECT TG.MADT
										FROM THAMGIADT TG
										WHERE TG.MAGV = GV.MAGV)
										)
					)
-- HAVING COUNT
SELECT GVQL.MAGV, GVQL.HOTEN, BM.TENBM
FROM GIAOVIEN TTGV JOIN GIAOVIEN GVQL ON TTGV.GVQLCM = GVQL.MAGV
	JOIN BOMON BM ON GVQL.MABM = BM.MABM
WHERE TTGV.MAGV IN (
					SELECT GV.MAGV
					FROM GIAOVIEN GV JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
						JOIN DETAI DT ON DT.MADT =TG.MADT
						JOIN CHUDE CD ON CD.MACD = DT.MACD
					WHERE CD.TENCD = N'Nghiên cứu phát triển'
					GROUP BY GV.MAGV, GV.HOTEN
					HAVING COUNT(DISTINCT TG.MADT) = (SELECT COUNT(DT1.MADT)
														FROM DETAI DT1 JOIN CHUDE CD1 ON CD1.MACD = DT1.MACD
														WHERE CD1.TENCD = N'Nghiên cứu phát triển')
					)