USE master
GO

USE QLDT
GO

--VD1: CHO BIẾT TÊN KHOA, MÃ KHOA, SỐ LƯỢNG GIÁO VIÊN VÀ LƯƠNG TRUNG BÌNH CỦA CÁC GIÁO VIÊN TỨNG KHOA

SELECT K.MAKHOA, K.TENKHOA, COUNT(GV.MAGV) AS SLGV, AVG(GV.LUONG) AS LUONGTB
FROM GIAOVIEN GV, BOMON BM, KHOA K
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = K.MAKHOA
GROUP BY K.MAKHOA, K.TENKHOA

-- VD2: CHO BIẾT LƯƠNG LỚN NHẤT CỦA GIÁO VIÊN NỨ BỘ MÔN CNPM

SELECT max(GV.LUONG) AS LUONGLONNHAT
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE GV.PHAI = N'Nữ' AND BM.TENBM = N'Công Nghệ Phần Mềm'

-- VD3: CHO BIẾT TRƯỞNG BỘ MÔN(MA, HOTEN) CÓ BỘ MÔN NHIỀU HƠN 2 GIÁO VIÊN

SELECT BM.MABM, TBM.MAGV, TBM.HOTEN
FROM GIAOVIEN GV, BOMON BM, GIAOVIEN TBM
WHERE GV.MABM = BM.MABM AND TBM.MAGV = BM.TRUONGBM
GROUP BY BM.MABM, TBM.MAGV, TBM.HOTEN
HAVING COUNT(gv.MAGV) > 2

--Q27: CHO BIẾT SỐ LƯỢNG GIAO VIÊN VÀ TỔNG LƯƠNG CỦA HỌ
SELECT COUNT(*) AS SLGV, SUM(GV.LUONG) AS TONGLUONG
FROM GIAOVIEN GV

-- Q28: CHO BIẾT SỐ LƯỢNG GIAO VIÊN VÀ LƯƠNG TRUNG BÌNH CỦA TỪNG BỘ MÔN
SELECT BM.MABM, COUNT(*) AS SLGV, AVG(ISNULL(GV.LUONG,0)) AS LUONGTB
FROM GIAOVIEN GV RIGHT JOIN  BOMON BM ON GV.MABM = BM.MABM
GROUP BY BM.MABM

-- Q29 CHO BIẾT TÊN CHỦ ĐỀ VÀ SỐ LƯỢNG ĐỀ TÀI THUỘC CHỦ ĐỀ ĐÓ
SELECT CD.TENCD, COUNT(DT.MADT) SLDT
FROM CHUDE CD LEFT JOIN DETAI DT ON CD.MACD = DT.MACD
GROUP BY CD.MACD, CD.TENCD

--Q30: CHO BIẾT TÊN GIAO VIÊN VÀ SỐ LƯỢNG ĐỀ TÀI MÀ GIAO VIÊN ĐÓ THAM GIA
SELECT GV.HOTEN, ISNULL(COUNT(DISTINCT TG.MADT),0) AS SOLUONGDT
FROM GIAOVIEN GV LEFT JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
GROUP BY GV.MAGV, GV.HOTEN

--Q31: CHO BIẾT TÊN GIAO VIÊN VÀ SỐ LƯỢNG ĐỀ TÀI MÀ GIAO VIÊN ĐÓ LÀM CHỦ NHIÊN
SELECT GV.HOTEN, COUNT(DISTINCT DT.MADT) SLDT
FROM GIAOVIEN GV LEFT JOIN DETAI DT  ON DT.GVCNDT = GV.MAGV
GROUP BY GV.MAGV, GV.HOTEN
-- Q32 VỚI MỖI GIAO VIÊN CHO TÊN GIAO VIÊN VÀ SỐ NGƯỜI THÂN CỦA GIÁO VIÊN ĐÓ
SELECT GV.HOTEN , COUNT(NT.TEN) AS SLNT
FROM GIAOVIEN GV LEFT JOIN NGUOITHAN NT ON GV.MAGV = NT.MAGV
GROUP BY GV.MAGV, GV.HOTEN

--Q33: CHO BIEENTS TÊN GIAO VIÊN ĐÃ THAM GIA TỪ 3 ĐỀ TÀI TRỞ LÊN
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV LEFT JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) >= 3

--Q34: CHO BIẾT SỐ LƯỢNG GIAO VIÊN ĐÃ THAM GIA VÀO ĐỀ TÀI ỨNG DỤNG HÓA HỌC XANH
SELECT count(DISTINCT TG.MAGV) SLGV
FROM THAMGIADT TG  JOIN DETAI DT ON TG.MADT = DT.MADT
WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
