use QLHocVien
go
SELECT * FROM GIAOVIEN
SELECT * FROM HOCVIEN
SELECT * FROM LOPHOC
SELECT * FROM GIAOVIEN_DAY_MONHOC
SELECT * FROM PHANCONG
SELECT * FROM MONHOC 
SELECT * FROM KETQUA
-- CÂU 1 CHO BIẾT THJOONG TIN LỚP TRƯỞNG (MÃ, HOTEN, TUỔI) CỦA LỚP HỌC CÓ SĨ SỐ DÔNG NHẤT KÊT THÚC TRƯỚC NĂM 2015
SELECT LT.MaHocVien, LT.TenHocVien, DATEDIFF(YEAR,LT.NgaySinh, GETDATE()) TUOI
FROM LOPHOC LH JOIN HOCVIEN HV ON HV.MaLop = LH.MaLop
				JOIN HOCVIEN LT ON LH.LopTruong = LT.MaHocVien
WHERE LH.NamKetThuc < 2015
GROUP BY LH.MaLop, LT.MaHocVien, LT.TenHocVien, LT.NgaySinh
HAVING COUNT(HV.MaHocVien) >= ALL( SELECT COUNT(HV1.MaHocVien)
									FROM LOPHOC LH1 JOIN HOCVIEN HV1 ON HV1.MaLop = LH1.MaLop
									WHERE LH1.NamKetThuc < 2015
									GROUP BY LH1.MaLop)
-- CÂU 2 CHO BIẾT THÔNG TIN NGƯỜI QUẢN LÝ MÃ TÊN CỦA GIÁO VIÊN ĐƯỢC PHẦN CÔNG GIẢNG DẠY CHO LỚP LH000001 NHIỀU LẦN NHẤT
SELECT GVQL.MaGV, GVQL.TenGV
FROM PHANCONG PC JOIN GIAOVIEN GV ON GV.MaGV = PC.MaGV
				JOIN GIAOVIEN GVQL ON  GVQL.MaGV = GV.MaGVQuanLi
WHERE PC.MaLop ='LH000001'
GROUP BY PC.MAGV,GVQL.MaGV, GVQL.TenGV
HAVING COUNT(DISTINCT PC.MaMH) >= ALL( SELECT COUNT(DISTINCT PC1.MaMH)
										FROM PHANCONG PC1
										WHERE PC1.MaLop ='LH000001'
										GROUP BY PC1.MAGV)

-- CÂU 3 CHO BIẾT THÔNG TIN GIÁO VIÊN(MÃ, TÊN) TỪNG ĐƯỢC PHÂN CÔNG DẠY TẤT CẢ CÁC LỚP CÓ SĨ SỐ TRÊN 1
--KQ: GIAOVIEN(MA,TEN)
--BC: PHANCONG(MAGV, MA LOP)
--C: LOPHOC(MALOP) SISO > 1
SELECT GV.MaGV, GV.TenGV
FROM GIAOVIEN GV JOIN PHANCONG PC ON GV.MaGV = PC.MaGV
	JOIN LOPHOC  LH ON LH.MaLop = PC.MaLop
WHERE LH.SiSo > 1
GROUP BY GV.MaGV, GV.TenGV
HAVING COUNT(DISTINCT LH.MaLop)  =  (SELECT COUNT(*)
									FROM LOPHOC LH1
									WHERE LH1.SiSo > 1)

SELECT GV.MaGV, GV.TenGV
FROM GIAOVIEN GV 
WHERE NOT EXISTS (SELECT * 
					FROM LOPHOC LH1
					WHERE LH1.SiSo > 1 AND NOT EXISTS (SELECT *		
														FROM PHANCONG PC
														WHERE PC.MaGV = GV.MaGV AND PC.MaLop = LH1.MaLop))

														GO
-- CÂU 4 
CREATE PROC sp_ThemPC @MAGV CHAR(10),@MAMH CHAR(10), @MALH CHAR(10)
AS
	IF(NOT EXISTS( SELECT * FROM GIAOVIEN GV WHERE GV.MaGV = @MAGV))
		RETURN -1 -- KHÒNG TÌM THẤY GIÁO VIÊN
	ELSE IF(NOT EXISTS( SELECT * FROM LOPHOC LH WHERE LH.MaLop = @MALH))
		RETURN -2 -- KHÔNG TÌM THẤY MÃ LỚP
	ELSE IF(NOT EXISTS( SELECT * FROM MONHOC MH WHERE MH.MaMonHoc = @MAMH))
		RETURN -3 -- KHÔNG TÌM THẤY MÔN HỌC
	ELSE
	BEGIN
		INSERT INTO PHANCONG(MaGV,MaLop, MaMH) VALUES(@MAGV,@MALH,@MAMH)

		UPDATE GIAOVIEN_DAY_MONHOC SET SoLopDaDay = ISNULL(SoLopDaDay,0) + 1 WHERE MaGV = @MAGV AND MaMH = @MAMH
		RETURN 1
	END
GO

DECLARE  @MAGV CHAR(10),@MAMH CHAR(10), @MALH CHAR(10), @R INT
SET @MAGV = 'GV00001'
SET @MALH = 'LH000002'
SET @MAMH = 'MH00001'

EXEC @R = sp_ThemPC @MAGV ,@MAMH , @MALH
PRINT @R


SELECT * FROM PHANCONG 
SELECT * FROM GIAOVIEN_DAY_MONHOC


--má đề 242
-- CÂU 1
SELECT GV.MaGV, GV.TenGV, DATEDIFF(YEAR,GV.NgaySinh, GETDATE()) TUOI
FROM GIAOVIEN GV JOIN LOPHOC LH ON GV.MaGV = LH.GVQuanLi
WHERE LH.NamBatDau >=2010 AND LH.SiSo >= ALL(SELECT SiSo FROM LOPHOC)
-- CÂU 2
SELECT LT.MaHocVien, LT.TenHocVien
FROM HOCVIEN LT  JOIN LOPHOC LH ON LH.LopTruong = LT.MaHocVien
				JOIN PHANCONG PC ON PC.MaLop = LH.MaLop

WHERE  PC. MaGV= 'GV00006'
GROUP BY PC.MaGV,LT.MaHocVien, LT.TenHocVien
HAVING COUNT(DISTINCT PC.MaMH) >= ALL(SELECT COUNT(DISTINCT PC1.MaMH)
									FROM PHANCONG PC1
									WHERE PC1.MaGV = 'GV00006'
									GROUP BY PC1.MaLop)
-- CÂU 3
-- R( SỐ BỊ CHIA): GIAOVIEN_DAY_MONHOC(MAGV, MAMG)
--S( SỐ CHIA): MONHOC(MAMH) SỐ TÍN CHỈ = 3
--T(THUONG): GIAOVIEN(MA,TEN)

SELECT GV.MaGV, GV.TenGV
FROM GIAOVIEN GV
WHERE NOT EXISTS( SELECT * 
				FROM MONHOC MH
				WHERE MH.SoChi = 3 AND NOT EXISTS( SELECT *
													FROM GIAOVIEN_DAY_MONHOC GV_MH
													WHERE GV_MH.MaMH = MH.MaMonHoc AND GV_MH.MaGV = GV.MaGV))
	  AND EXISTS ( SELECT * FROM MONHOC WHERE SoChi = 3)

SELECT GV.MaGV, GV.TenGV
FROM GIAOVIEN GV JOIN GIAOVIEN_DAY_MONHOC GV_MH ON GV.MaGV = GV_MH.MaGV
	JOIN MONHOC MH ON GV_MH.MaMH = MH.MaMonHoc
WHERE MH.SoChi = 3
GROUP BY GV.MaGV, GV.TenGV
HAVING COUNT(DISTINCT MH.MaMonHoc) = (SELECT COUNT(*)
										FROM MONHOC MH
										WHERE MH.SoChi =3)